# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'
  
before_install:
  - sudo apt-get install jags
  - sudo apt-get install r-cran-rjags
  - sudo apt-get install r-cran-rstan
  - sudo apt-get install r-cran-rstanarm
  - sudo apt-get install r-cran-mcmcpack
  - sudo apt-get install r-cran-igraph
  - sudo apt-get install r-cran-bh
  - sudo apt-get install r-cran-openssl
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars

after_success:
  - Rscript -e 'covr::codecov()'
